// Radar creator — catalogo dei format (studio del 9/10/2026, dal Trend Finder di CreatorsPro e
// ricerca web). Format GIÀ ESISTENTI e provati, quasi assenti in Italia; per ora solo quelli che
// la ragazza fa da sola in casa (decisione di Nicholas), gli altri "per dopo".
// I dati interni (account a tema delle nostre creator) vengono dalle statistiche CreatorsPro
// 8 agosto – 8 ottobre 2026. Contenuto statico: si aggiorna quando si rifà lo studio.

export const FORMAT_ASOF = "ottobre 2026";

export const OUR_CONCEPTS = [
  { name: "In viaggio", who: "Iri", before: "1,48 M", after: "2,42 M" },
  { name: "Psicologa di strada", who: "Claudia Surace", before: "129k", after: "193k" },
  { name: "Camionista", who: "Iri", before: "77k", after: "89k" },
  { name: "Elevator", who: "Sara Sfamurri", before: "47k", after: "64k" },
  { name: "Nerd, Cosplay, Dominatrice, Poliziotta, Office girl, Casalinga, School girl", who: "vari", before: "0 reel", after: "0 reel", dead: true },
];

export const FORMAT_TESTS = [
  ["Si può fare cento volte senza ripetersi?", "Se dopo dieci episodi le idee finiscono, è uno sketch, non un format."],
  ["Si riconosce nel primo secondo?", "Un'inquadratura, una frase o un oggetto fisso: chi l'ha già visto capisce subito chi è."],
  ["È legato a lei?", "Se domani lo fa una qualunque ragazza uguale, non le costruisce un'identità."],
  ["Dà un motivo per tornare?", "Un numero di puntata, una storia che continua, un verdetto da aspettare."],
  ["Fa venire voglia di conoscerla di più?", "È il passaggio verso OF. Un reel che fa solo ridere porta view, non abbonati."],
];

export const FORMAT_CHOICE = [
  ["Cosa ha di unico?", "Un tratto fisico (altezza, tatuaggi, capelli), un mestiere vero, una città o un paese, una passione (gaming, anime, palestra, cucina), un accento. Porta a: identità come marchio, ruolo, provincia, ragazza italiana per l'estero."],
  ["Cosa sa fare davanti alla camera?", "Se parla bene e fa ridere: personaggi, giudice, giudica le frasi dei follower. Se è a suo agio solo in silenzio: serie numerate, rituali, percorsi."],
  ["Quanta vicinanza regge?", "Alta: POV «la tua ragazza», prepararsi insieme, buongiorno e buonanotte. Media: giudice, domande al pubblico. Bassa: personaggi comici, da usare come vetrina più che come passaggio a OF."],
];

export const FORMAT_TRIAL = [
  ["Settimana 0", "Si scelgono due format e si scrivono i primi 10 episodi di ciascuno. Se non si arriva a 10 idee a tavolino, il format non è adatto a lei: si cambia prima di girare."],
  ["Settimane 1–3", "Tre episodi a settimana per format, sempre con la stessa apertura. Il resto del feed continua come prima."],
  ["Cosa guardare", "Prima i nuovi abbonati OF per milione di view, poi i commenti che chiedono la puntata dopo, per ultime le view."],
  ["Decisione", "Il format che porta più abbonati per milione di view del feed attuale diventa la colonna del profilo, per mesi. Quello che porta solo view resta come contorno."],
];

// fam = famiglia; free = libero in Italia; hi = avvicina molto a OF; zero = costo zero; later = servono altre persone o uscire
export const FORMATS = [
  { fam: "Serie a puntate", name: "Giorno X di…", mech: "Fisso: un obiettivo e il contatore («Giorno 5 di 31»). Cambia: il progresso di ogni giorno.", who: "queenfesch6, «31 cosplay in 31 giorni»: 11 degli 80 reel in tendenza nel Trend Finder, fino a 2,3 M di view a puntata.", why: "La storia è aperta: si torna per vedere a che punto è arrivata.", evolve: "Finita una sfida se ne annuncia un'altra, oppure si alza l'obiettivo.", it: "Nessuna serie numerata lunga trovata tra le creator italiane.", free: 1, hi: 0, zero: 1 },
  { fam: "Serie a puntate", name: "Il giudice fisso", mech: "Fisso: il voto e chi lo dà. Da sola: il giudice è il pubblico, che vota nei commenti. Cambia: cosa viene giudicato (outfit, cena, capelli).", who: "mananamariee (29,4 M di follower), shelbyywilfong (1,7 M), muizandjae (1,5 M): «il mio ragazzo vota il mio outfit».", why: "Il pubblico tifa e aspetta il verdetto.", evolve: "Nella versione originale giudica il fidanzato: da noi parte già con il pubblico, così non serve nessun altro in camera.", it: "Nessun equivalente italiano con massa critica trovato.", free: 1, hi: 0, zero: 1 },
  { fam: "Serie a puntate", name: "Diario verso una data", mech: "Fisso: un traguardo dichiarato (un anniversario, un trasferimento). Cambia: l'episodio di vita di quel giorno.", who: "Ling and Lamb, 2,5 M di follower su TikTok, diario a cadenza fissa.", why: "La data nota crea un traguardo da festeggiare insieme al pubblico.", evolve: "Raggiunta la data, se ne fissa una nuova.", it: "Nessun caso italiano trovato.", free: 1, hi: 0, zero: 1 },
  { fam: "Personaggi", name: "POV «la tua ragazza»", mech: "Fisso: lei parla in camera come se lo spettatore fosse il suo ragazzo. Cambia: la situazione (gelosia, dolcezza, una lite buffa).", who: "mikaelahappas, serie «POV: your girlfriend is on a date» arrivata alla parte 9. Imitato da molti account minori.", why: "Parla direttamente a chi guarda: è il format con più vicinanza di tutti.", evolve: "Le situazioni non finiscono mai: da fidanzati, al primo appuntamento, dopo la rottura.", it: "Enorme in inglese, nessuna creator italiana trovata con massa critica. È lo spazio libero più interessante.", free: 1, hi: 1, zero: 1 },
  { fam: "Personaggi", name: "Personaggi ricorrenti", mech: "Fisso: uno o più personaggi con frasi, tic e costume riconoscibili. Cambia: la situazione in cui finiscono.", who: "Benny Drama (1,6 M su TikTok). In Italia Mattia Stanga (1,4 M). Da noi: «Psicologa di strada», 193k view a reel.", why: "Il pubblico riconosce il tipo e segue più personaggi nello stesso account.", evolve: "Si aggiunge un personaggio nuovo, o una spalla fissa.", it: "Esiste in Italia, ma solo come comicità generalista. Nessuna creator lo usa per avvicinare a sé.", free: 0, hi: 0, zero: 1 },
  { fam: "Personaggi", name: "Ruolo o mestiere", mech: "Fisso: un ruolo riconoscibile (infermiera, prof, vicina di casa), recitato in casa parlando in camera. Cambia: la scenetta.", who: "whoispiperpresley2.0, scenette di ruolo (6 reel su 80 nel Trend Finder). Mestiere vero: morgandrinkscoffee, 6,1 M. Da noi: «Camionista» di Iri.", why: "Si vede da dentro un mondo che si conosce solo da fuori.", evolve: "Arrivano colleghi e clienti fissi, il turno diventa una serie.", it: "Nessuna creator italiana trovata, soprattutto sui mestieri fisici.", free: 1, hi: 1, zero: 0 },
  { fam: "Domande al pubblico", name: "Giudica le frasi dei follower", mech: "Fisso: lei legge e vota da 1 a 10 le frasi per rimorchiare scritte nei commenti. Cambia: le frasi, che scrivono loro.", who: "Trend molto diffuso, nessun account «proprietario» verificato: è ancora di chi lo prende per primo.", why: "Ogni follower spera di essere letto: commenta e torna.", evolve: "La peggiore della settimana, l'appello, la sfida tra due follower.", it: "Nessun caso italiano trovato.", free: 1, hi: 1, zero: 1 },
  { fam: "Domande al pubblico", name: "Indovina età o altezza", mech: "Fisso: la domanda. Cambia: outfit e situazione.", who: "Diffuso, nessun account proprietario verificato.", why: "La sorpresa fa commentare.", evolve: "Si passa ad altre domande su di lei: da dove vengo, che lavoro faccio.", it: "Nessun caso italiano trovato.", free: 1, hi: 0, zero: 1 },
  { fam: "Domande al pubblico", name: "Rispondo al tuo commento", mech: "Fisso: il commento di un follower mostrato a schermo, lei risponde in video. Cambia: il commento scelto.", who: "Funzione nativa di Instagram e TikTok, usata ovunque. Vince chi la usa con costanza.", why: "Chi commenta spera di essere scelto, e i commenti diventano il copione.", evolve: "Si fissa una rubrica: la domanda più strana della settimana, il commento più dolce.", it: "Usato in modo sparso, nessuna creator lo tiene come appuntamento fisso.", free: 1, hi: 1, zero: 1 },
  { fam: "Identità", name: "Un tratto fisico come marchio", mech: "Fisso: il tratto («sono alta 1,90»). Cambia: ogni situazione raccontata attraverso quel tratto.", who: "ekaterina_lisina15, 2,06 m, «The Tall House» (fino a 4,6 M di view). iamimaniali, 350k.", why: "Chi si riconosce resta, chi è curioso guarda.", evolve: "Dalla moda alla vita di tutti i giorni, sempre vista attraverso il tratto.", it: "Nessuna creator italiana con questo posizionamento.", free: 1, hi: 1, zero: 1 },
  { fam: "Identità", name: "Gamer o cosplay", mech: "Fisso: il fandom (un gioco, un anime). Cambia: personaggio, costume, gioco del giorno.", who: "Jessica Nigri, 3,6 M su Instagram. ember.w0lf, 3,2 M su TikTok.", why: "Fandom fedeli e maschili, già abituati a spendere.", evolve: "Ogni gioco o anime nuovo è una stagione nuova.", it: "Nessuna cosplayer italiana di peso trovata, con Lucca Comics a disposizione.", free: 1, hi: 1, zero: 0 },
  { fam: "Identità", name: "La ragazza italiana, per chi è all'estero", mech: "Fisso: l'accento e la cultura italiana. Cambia: frasi, situazioni «da fidanzata italiana», piccole lezioni.", who: "«Learn Italian with Ale», bthenomad. «Italian girlfriend effect» è un trend riconosciuto su TikTok.", why: "L'accento italiano piace al pubblico straniero, ed è facile da condividere.", evolve: "Dalla lezione di lingua al flirt in italiano.", it: "Quasi tutte fanno didattica pura. La versione flirt è libera, e il pubblico straniero è quello che paga.", free: 1, hi: 1, zero: 1 },
  { fam: "Identità", name: "La ragazza di provincia", mech: "Fisso: la vita vera di un paese, casa, famiglia. Cambia: i piccoli eventi locali.", who: "Brooke Monk negli Stati Uniti (girl next door).", why: "Sembra vera e raggiungibile.", evolve: "Diventa un racconto: il paese, la sagra, il contrasto con la città.", it: "Nessuna creator italiana posizionata così.", free: 1, hi: 1, zero: 1 },
  { fam: "Rituali", name: "Prepararsi insieme raccontando (GRWM)", mech: "Fisso: trucco e vestiti davanti allo specchio. Cambia: la storia raccontata nel frattempo.", who: "alixearle, 8,3 M su TikTok. Il genere «get ready with me» supera i 70 miliardi di view.", why: "Sembra di essere in bagno con lei mentre si confida.", evolve: "Dal tutorial al racconto a puntate della sua vita.", it: "Nessuna creator italiana ne ha fatto il suo marchio.", free: 1, hi: 1, zero: 1 },
  { fam: "Rituali", name: "Buongiorno e buonanotte", mech: "Fisso: l'orario e la frase. Cambia: come si sveglia, come va a dormire.", who: "the.kalirene: 3 reel su 80 nel Trend Finder, fino a 2,5 M di view.", why: "È un appuntamento fisso: il più simile a quello che si compra su OF.", evolve: "Si aggiungono domande del pubblico.", it: "Diffuso in modo sparso, nessuna creator lo usa come colonna del profilo.", free: 0, hi: 1, zero: 1 },
  { fam: "Rituali", name: "Cosa mangio in un giorno", mech: "Fisso: la struttura colazione, pranzo, cena. Cambia: cosa cucina e come lo racconta.", who: "Genere da 9,8 miliardi di view.", why: "Bassissimo sforzo, curiosità per la vita privata.", evolve: "Dalla dieta al racconto della giornata. Evitare il conteggio delle calorie, che crea polemiche.", it: "Molto diffuso, nessuna creator-marchio italiana.", free: 0, hi: 0, zero: 1 },
  { fam: "Percorsi", name: "Trasformazione a tappe", mech: "Fisso: il controllo periodico, sempre uguale (prima/dopo, numeri). Cambia: i progressi.", who: "LeanBeefPatty, 8,3 M su TikTok. Molte creator minori con «100 giorni».", why: "Si torna per sapere come finisce.", evolve: "Dal corpo alla storia: difficoltà, motivazione, relazioni.", it: "Nessuna creator italiana trovata su questo percorso.", free: 1, hi: 0, zero: 1 },
  { fam: "Per dopo", later: 1, name: "Chi scegli? A-B-C-D-E", mech: "Cinque ragazze in fila con una lettera e una domanda. Cambia: la domanda.", who: "thedandangler: 10,3 M di view sul reel in testa al Trend Finder.", it: "Nessun caso italiano. Noi abbiamo 60 creator per farlo." },
  { fam: "Per dopo", later: 1, name: "Intervista per strada", mech: "Lei ferma la gente e fa la stessa domanda su appuntamenti e tipi ideali.", who: "stellaandrewsss, circa 1,6 M su Instagram.", it: "Esiste come comicità, nessuna creator lo usa come format suo." },
  { fam: "Per dopo", later: 1, name: "La casa delle creator", mech: "Un gruppo di creator che vive o gira insieme.", who: "Bop House (Sophie Rain, Aishah Sofey, Camilla Araujo): circa 90 M di follower in totale.", it: "Esistono case italiane solo lifestyle. Nessuna legata a profili a pagamento." },
  { fam: "Per dopo", later: 1, name: "Il gruppo fisso di amiche", mech: "Le stesse 3-5 ragazze, cambia il gioco o la sfida.", who: "stellaandrewsss con le amiche, 2,3 M di view.", it: "Nessun caso italiano trovato." },
  { fam: "Per dopo", later: 1, name: "Il viaggio a puntate", mech: "Lei in viaggio, cambia il posto.", who: "Da noi: «In viaggio» di Iri, 2,4 M di view a reel e in crescita.", it: "Funziona già da noi: è il nostro esempio migliore." },
];
