SELECT
  creator_id,
  SUM(CASE WHEN calendar_date = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) THEN total ELSE 0 END) AS reach_yesterday,
  SUM(CASE WHEN calendar_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) THEN total ELSE 0 END) AS reach_3d,
  SUM(CASE WHEN calendar_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) THEN total ELSE 0 END) AS reach_7d,
  SUM(CASE WHEN calendar_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 14 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) THEN total ELSE 0 END) AS reach_14d,
  SUM(CASE WHEN calendar_date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 28 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) THEN total ELSE 0 END) AS reach_28d
FROM
  hoc.reach
GROUP BY
  creator_id
ORDER BY
  reach_28d DESC;
