SELECT
  date_key,
  id,
  platform_id,
  video_id AS video_id_key,
  commit_timestamp,
  batch_timestamp,
  author_unique_id,
  create_time,
  aweme_id,
  region,
  duration,
  CONCAT('https://www.tiktok.com/@', author_unique_id, '/video/', video_id) AS url,
  music_id,
  music_play,
  thumbnail_url,
  play_count,
  IF(DATE(create_time) = date_key, play_count, play_count - IFNULL(LAG(play_count) OVER(PARTITION BY id, video_id ORDER BY date_key), play_count)) AS play_count_diff,
  comment_count,
  IF(DATE(create_time) = date_key, comment_count, comment_count - IFNULL(LAG(comment_count) OVER(PARTITION BY id, video_id ORDER BY date_key), comment_count)) AS comment_count_diff,
  digg_count,
  IF(DATE(create_time) = date_key, digg_count, digg_count - IFNULL(LAG(digg_count) OVER(PARTITION BY id, video_id ORDER BY date_key), digg_count)) AS digg_count_diff,
  share_count,
  IF(DATE(create_time) = date_key, share_count, share_count - IFNULL(LAG(share_count) OVER(PARTITION BY id, video_id ORDER BY date_key), share_count)) AS share_count_diff,
  download_count,
  IF(DATE(create_time) = date_key, download_count, download_count - IFNULL(LAG(download_count) OVER(PARTITION BY id, video_id ORDER BY date_key), download_count)) AS download_count_diff,
  collect_count,
  IF(DATE(create_time) = date_key, collect_count, collect_count - IFNULL(LAG(collect_count) OVER(PARTITION BY id, video_id ORDER BY date_key), collect_count)) AS collect_count_diff,
  caption,
  1 AS posts_count,
  CASE date_key = DATE(create_time, 'UTC') WHEN TRUE THEN 1 ELSE 0 END AS posts_count_diff,
  organization_id
FROM
  `house-of-creators-358213.tiktok.posts_gaps_filled`