SELECT
  date_key,
  owner_id,
  id,
  fbid,
  --min_commit_date,
  --commit_date,
  owner_full_name,
  create_time,
  CONCAT('https://www.instagram.com/reel/', code, '/') AS video_url,
  CONCAT('https://www.instagram.com/reels/audio/', music_code, '/') AS music_url,
  thumbnail_url,
  play_count,
  GREATEST(play_count - IFNULL(LAG(play_count) OVER(PARTITION BY id ORDER BY date_key), play_count), 0) AS play_count_diff,
  fb_play_count,
  GREATEST(fb_play_count - IFNULL(LAG(fb_play_count) OVER(PARTITION BY id ORDER BY date_key), fb_play_count), 0) AS fb_play_count_diff,
  like_count,
  GREATEST(like_count - IFNULL(LAG(like_count) OVER(PARTITION BY id ORDER BY date_key), like_count), 0) AS like_count_diff,
  comment_count,
  GREATEST(comment_count - IFNULL(LAG(comment_count) OVER(PARTITION BY id ORDER BY date_key), comment_count), 0) AS comment_count_diff,
  caption,
  --filled,
  music_title,
  music_duration_ms,
  music_download_url,
  1 AS reels_count,
  CASE date_key = DATE(create_time, 'UTC') WHEN TRUE THEN 1 ELSE 0 END AS reels_count_diff
FROM
  `house-of-creators-358213.trendfinder.reels_gaps_filled`